# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # to install diepencies
    - run: npm run build --if-present
    #runs the script "build"
    - run: npm test
    #this runs a predefined command specified in the test.
    - run: git config user.email "automation@canariatechnologies.com"
    #to set git configuration settings
    - run: git config user.name "automation"
    #to set git configuration settings
    - run: git fetch
    #gets the vommits and files
    - run: git checkout publish || git checkout --orphan publish
    #navigate to publish branch and create new branch 
    - run: cp -r build/* .
    #copy build folder
    - run: git add .
    #adds all the modified and new files 
    - run: git commit -m "Publish build"
    #creates a snapshot of current changes
    - run: git push --set-upstream origin publish
    #setting upstream branch